//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoidung
    {
        public string ID { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string groupID { get; set; }
        public string ten { get; set; }
    
        public virtual GroupU GroupU { get; set; }
    }
}
